name: tech_station
description: "Tech Station â€” Your one-stop device knowledge hub."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.7
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

  # Routing
  go_router: ^14.8.1

  # Backend / Auth
  supabase_flutter: ^2.9.0
  google_sign_in: ^6.2.2

  # Architecture
  get_it: ^8.0.3
  dartz: ^0.10.1

  # Utilities
  intl: ^0.20.2
  share_plus: ^10.1.4
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
